version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: world-db
    restart: always
    environment:
      MYSQL_DATABASE: world
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql